### ISSUE TITLE
Meta4 content is not displayed anymore in my browser

### ISSUE THREAD

**Issue by benoit74** [kiwix/mirrorbrain#4]
Few weeks / months ago, metalink links like https://download.kiwix.org/zim/gutenberg/gutenberg_af_all_2023-08.zim.meta4 were properly displayed as a "nice" HTML page (probably through a stylesheet).

Now it just download the XML file.

Not sure this is linked to "the big change", but probably.

@rgaudin any idea how it worked before? I can have a look if you have no idea.

**Comment by rgaudin** [comment]
Pretty sure you're mistaken with https://download.kiwix.org/zim/gutenberg/gutenberg_af_all_2023-08.zim?mirrorlist
